### ISSUE TITLE
[GSoC Project Proposal]: IOOS_QC WebApp

### ISSUE THREAD

**Issue by ocefpaf** [ioos/gsoc#63] opened 2024-11-14 18:14 UTC
### Project Description

Create a Web App using pyscript and/or pyodide

### Expected Outcomes

A user should be able to update a dataset and select the data checks they want to apply to it. Here is a prototype:

### Expected Project Size

None

### What is the difficulty of the project?

None

**Comment by MathewBiddle** [comment] 2024-11-15 15:07
Looks like this is a duplicate of #64 Closing.

**Closed by MathewBiddle** 2024-11-15 15:07 UTC
Labels: project idea, GSoC24

**Comment by ocefpaf** [comment] 2024-11-15 17:15
I probably hit some key combination that opened this one before I finished typing. Sorry for the noise.
